
package com.dhenton9000.sec.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecurityServiceImplService", targetNamespace = "http://sec.cxf.dhenton9000.com/", wsdlLocation = "http://localhost:8080/cxf-java-first/SecurityService?wsdl")
public class SecurityServiceClient
    extends Service
{

    private final static URL SECURITYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECURITYSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SECURITYSERVICEIMPLSERVICE_QNAME = new QName("http://sec.cxf.dhenton9000.com/", "SecurityServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/cxf-java-first/SecurityService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECURITYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SECURITYSERVICEIMPLSERVICE_EXCEPTION = e;
    }
    
    
    
    public static void main(String[] args) {
        
        SecurityServiceClient impl = new SecurityServiceClient();
        
        SecurityService service = impl.getSecurityServiceImplPort();
        
        List<Group> groups = service.getGroups();
        
        groups.forEach(g -> {
           System.out.println(g.getGroupName());
        
        });
         
    }
    
    
    

    public SecurityServiceClient() {
        super(__getWsdlLocation(), SECURITYSERVICEIMPLSERVICE_QNAME);
    }

    public SecurityServiceClient(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECURITYSERVICEIMPLSERVICE_QNAME, features);
    }

    public SecurityServiceClient(URL wsdlLocation) {
        super(wsdlLocation, SECURITYSERVICEIMPLSERVICE_QNAME);
    }

    public SecurityServiceClient(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECURITYSERVICEIMPLSERVICE_QNAME, features);
    }

    public SecurityServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityServiceClient(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecurityService
     */
    @WebEndpoint(name = "SecurityServiceImplPort")
    public SecurityService getSecurityServiceImplPort() {
        return super.getPort(new QName("http://sec.cxf.dhenton9000.com/", "SecurityServiceImplPort"), SecurityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecurityService
     */
    @WebEndpoint(name = "SecurityServiceImplPort")
    public SecurityService getSecurityServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sec.cxf.dhenton9000.com/", "SecurityServiceImplPort"), SecurityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECURITYSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SECURITYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SECURITYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }
    
    
    

}
